### PR TITLE
Second Approach to outsource configuration files

### PR DESCRIPTION
**Pull request by anghenfil**
Implementation of new config with phpdotenv. See Issue #1!

### CODE REVIEW

**Comment by luap42** [comment]
Hello, thank you for opening this PR as an alternative to #2. But I personally do not like the implementation of the field SITE_NAMES. Is there no field in .env files for key-value-pairs? Because if not I suppose this solution is harder to maintain than the JSON-based approach.

**Comment by anghenfil** [comment]
No there is no possibility in .env files, because it's against the basic idea of environment variables. I think with the new SiteManager class it isn't a problem to access the SITE_NAMES field. I think, that maintaining the phpdotenv solution is much easier.

**Comment by luap42** [comment]
As we can assume that JSON is a common format and we know that JSON supports dictionarys whilst in .env you are required to introduce a non-common syntax, in my opinion JSON is the more-comfortable approach. You could also use the ini-file-format that is close to the .env format. PHP allows you to parse it and supports dictionaries and lists: http://php.net/manual/en/function.parse-ini-file.php

**Comment by anghenfil** [comment]
Env files are common in linux related world. They come from environment variables.

**Pull request merged**
