### PR TITLE
Outsourcing configuration files

### PR DESCRIPTION
**Pull request by luap42**
Moving configuration to /secret/configuration.cfg, Protecting /secret
with .htaccess, Loading configuration in config.php

Based on Issue #1

### CODE REVIEW

**Comment by anghenfil** [comment]
Hi,
I think it would be better to create a Configuration php class, which loads stored configuration. 
For example:
`<?php
class Configuration{
  getConfig($key){
    etc.
  }
}`

**Comment by luap42** [comment]
@anghenfil I just re-implemented the previous code with the change: import config from /secret/config.cfg

**Comment by schiederme** [comment]
Hey, there is a easy way like [phpdotenv](https://packagist.org/packages/vlucas/phpdotenv). It dosen't require much work, its availabel via composer and its rely esay to use.

**Comment by schiederme** [comment]
Sorry, I don't get a mail from the issue.

**Comment by anghenfil** [comment]
I think using phpdotenv is a really good idea. It seems to be more secure and easy. I will implement phpdotenv in another pull request.

**Comment by luap42** [comment]
# Please look at my post to Issue #1 related to .env's security:

> Hello, I have just created a .env file under my Apache XAMPP installation root and were able to show it via localhost/.env. So I do not suppose that this type is more secure than my proposal. AFAIK Apache only hides .ht* files.

**Pull request closed without merging**
